.python_venv:
  image: python:3
  before_script:
    - python3 -m venv .venv
    - source .venv/bin/activate
    - python -V
    - pip install -r requirements.txt

test_generation:
  stage: test
  extends: .python_venv
  script:
    - cd proto
    - python tests.py

test_interaction:
  rules:
    - if: $NO_GHDL == null
  stage: test
  extends: .python_venv
  script:
    - cd testfiles/tb
    - ./run.sh

documentation:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
      - doc/**/*
  cache:
    - key:
        files:
          - doc/Gemfile.lock
      paths:
        - doc/vendor/bundle
  artifacts:
    paths:
      - doc/*.pdf
  script:
    - cd doc
    - bundle config set --local path 'vendor/bundle'
    - bundle install
    - make all

deploy:
  stage: deploy
  only:
    - master
    - tags
  tags:
    - cheby-cd
  script:
    - source integration/cern-ci.sh
