-- Do not edit; this file was generated by Cheby using these options:
--  --gen-hdl -i cern_info.cheby

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity cregs is
  port (
    Clk                  : in    std_logic;
    Rst                  : in    std_logic;
    VMEAddr              : in    std_logic_vector(19 downto 2);
    VMERdData            : out   std_logic_vector(31 downto 0);
    VMEWrData            : in    std_logic_vector(31 downto 0);
    VMERdMem             : in    std_logic;
    VMEWrMem             : in    std_logic;
    VMERdDone            : out   std_logic;
    VMEWrDone            : out   std_logic;
    VMERdError           : out   std_logic;
    VMEWrError           : out   std_logic;
    test1_o              : out   std_logic_vector(31 downto 0)
  );
end cregs;

architecture syn of cregs is
  signal rd_ack_int                     : std_logic;
  signal wr_ack_int                     : std_logic;
  signal test1_reg                      : std_logic_vector(31 downto 0);
  signal test1_wreq                     : std_logic;
  signal test1_wack                     : std_logic;
  signal mapver_rint                    : std_logic_vector(31 downto 0);
  signal icode_rint                     : std_logic_vector(31 downto 0);
  signal rd_ack_d0                      : std_logic;
  signal rd_dat_d0                      : std_logic_vector(31 downto 0);
  signal wr_req_d0                      : std_logic;
  signal wr_adr_d0                      : std_logic_vector(19 downto 2);
  signal wr_dat_d0                      : std_logic_vector(31 downto 0);
begin
  VMERdDone <= rd_ack_int;
  VMEWrDone <= wr_ack_int;

  -- pipelining for wr-in+rd-out
  process (Clk) begin
    if rising_edge(Clk) then
      if Rst = '0' then
        rd_ack_int <= '0';
        wr_req_d0 <= '0';
      else
        rd_ack_int <= rd_ack_d0;
        VMERdData <= rd_dat_d0;
        wr_req_d0 <= VMEWrMem;
        wr_adr_d0 <= VMEAddr;
        wr_dat_d0 <= VMEWrData;
      end if;
    end if;
  end process;

  -- Register test1
  test1_o <= test1_reg;
  process (Clk) begin
    if rising_edge(Clk) then
      if Rst = '0' then
        test1_reg <= "00000000000000000000000000000000";
        test1_wack <= '0';
      else
        if test1_wreq = '1' then
          test1_reg <= wr_dat_d0;
        end if;
        test1_wack <= test1_wreq;
      end if;
    end if;
  end process;

  -- Register mapver
  mapver_rint(31 downto 0) <= "00000001001100111010001000000111";

  -- Register icode
  icode_rint(31 downto 0) <= "00000000000000000000000000010001";

  -- Process for write requests.
  process (wr_adr_d0, wr_req_d0, test1_wack) begin
    test1_wreq <= '0';
    case wr_adr_d0(19 downto 2) is
    when "000000000000000000" => 
      -- test1
      test1_wreq <= wr_req_d0;
      wr_ack_int <= test1_wack;
    when "000000000000000001" => 
      -- mapver
      wr_ack_int <= wr_req_d0;
    when "000000000000000010" => 
      -- icode
      wr_ack_int <= wr_req_d0;
    when others =>
      wr_ack_int <= wr_req_d0;
    end case;
  end process;

  -- Process for read requests.
  process (VMEAddr, VMERdMem, test1_reg, mapver_rint, icode_rint) begin
    -- By default ack read requests
    rd_dat_d0 <= (others => 'X');
    case VMEAddr(19 downto 2) is
    when "000000000000000000" => 
      -- test1
      rd_ack_d0 <= VMERdMem;
      rd_dat_d0 <= test1_reg;
    when "000000000000000001" => 
      -- mapver
      rd_ack_d0 <= VMERdMem;
      rd_dat_d0 <= mapver_rint;
    when "000000000000000010" => 
      -- icode
      rd_ack_d0 <= VMERdMem;
      rd_dat_d0 <= icode_rint;
    when others =>
      rd_ack_d0 <= VMERdMem;
    end case;
  end process;
end syn;
